// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("StringReaderProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("StringReaderProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing StringReaderProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "StringReaderProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "StringReaderProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing StringReaderProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
